apiVersion: v1
kind: Service
metadata:
  name: gps-microservice-service
spec:
  selector:
    app: gps-microservice
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
